name: Sean Barton
sitename: Sean Barton - Personal Site
title: This is the site title

markdown: kramdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

timezone: America/New_York
future: true
theme: minima
